name: Check Pull Request

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - master
      - release/*
      - hotfix/*
  pull_request:
    branches-ignore:
      - tag/*
jobs:
  test-arm64:
    runs-on: ubuntu-20.04
    name: Test with arm64 OpenJDK 11
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Build with arm64 OpenJDK 11
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./.github/workflows/Dockerfile.3.8.1-openjdk-11
          platforms: linux/arm64
          push: false
  test-ppc64le:
    runs-on: ubuntu-20.04
    name: Test with ppc64le IbmJDK 8
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Build with ppc64le IbmJDK 8
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./.github/workflows/Dockerfile.3.8.1-ibmjava-8
          platforms: linux/ppc64le
          push: false